apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: FIXME_2
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 7000
